### PR TITLE
reorganize cython build; working on os x

### PR DESCRIPTION
**Pull request by kwmsmith**
@ajfriend -- this should work now on OS X at least.  Still having issues porting over the manylinux build.

### CODE REVIEW

**Comment by isaacbrodsky** [comment]
It looks like CI (Appveyor) is failing, perhaps related to the files being moved in this PR? Is that expected?

**Comment by ajfriend** [comment]
Apologies I didn't see this until this morning! (I was on vacation last week, and only periodically checking #41)

I clone the PR, but I'm still getting an install issue when I run `make init`. @isaacbrodsky, could you check to see if you have the same issue?

[Here is the output I'm seeing.](https://gist.github.com/ajfriend/61935102efe4cf8b49c41b160b5e7bd9)

**Comment by isaacbrodsky** [comment]
I got a very similar output when I tried running on OSX. I added `LANGUAGES C` to line 16 (project definition) in `CMakeLists.txt`. After that I reran `make init` and it seemed to build successfully, I was able to run `h3.geo_to_h3(0, 0, 0)` from IPython.

**Comment by ajfriend** [comment]
That worked for me. I made the following changes

- changed the project definition in `CMakeLists.txt` to `project(h3core-py VERSION "${version}" LANGUAGES C)`
- added `env/bin/pip install dist/*.whl` to the `make init` rule
- changed the import at the top of `tests/test.py` to `from h3 import h3`

**Comment by ajfriend** [comment]
@kwmsmith @isaacbrodsky If the CI issues are easy, we should go ahead and fix. If not, I don't think we should block on it. I'd lean towards just merging this and trying to fix them in a future PR. If this version runs on our machines, then I can start merging in my changes to help move things along.

What do you all think?

**Comment by kwmsmith** [comment]
> What do you all think?

✅ -- sounds good to me.

**Pull request merged**
